server:
  port: 8080
  servlet:
    context-path: /backend
    session:
      cookie:
        name: UISESSION

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Kotlin_OAuth2?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      initial-size: 15
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 8
      default-auto-commit: true
      test-on-borrow: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false
    generate-ddl: true
    show-sql: true